name: Practitioner Guide Proposal
title: "[Practitioner Guide]: TOPIC"
description: Use this template to propose new CHAOSS Practitioner Guides
labels: ['practitioner guide', 'proposal']
assignees:
  - geekygirldawn

body:
  - type: markdown
    attributes:
      value: | 
        To avoid duplication and re-work, we ask you to use this template to propose new CHAOSS Practitioner Guides. While metrics models are designed with collections of metrics that can be implemented together, these Practitioner Guides are different from metrics models. Practitioner guides are designed to help us humans understand how to interpret metrics within a narrow topic and make improvements based on what is learned from that interpretation. Each Practitioner Guide should focus on 2-4 metrics, but can include a list of additional metrics in Step 3 - Gather Additional Data if needed.

  - type: markdown
    attributes:
      value: |
        ## Practitioner Guide Information

  - type: input
    attributes:
      label: Practitioner Guide Topic (1 - 3 words)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Is this a getting started guide or a more advanced guide for experienced users?
      options:
        - Getting Started
        - Advanced / Expert
        - Not sure
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Primary Metrics (2 - 4 metrics for Getting Started Guides)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this topic important? How will this help people improve their open source project and / or community? Who will benefit from this guide?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: How would you like to see this guide developed?
      options:
        - I am interested in using this guide, but I do not want to write it myself
        - I have the experience and time available to write the first draft
        - I would like to help write the guide, but I need someone with more experience in the topic to help me
        - Other (please specify in the “Additional Notes” at the end of this form)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Notes
    validations:
      required: false

